### ISSUE TITLE
Getting an error when searching by ID

### ISSUE THREAD

**Issue by SylveonDeko** [cainy-a/Anilist4Net#4]
System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable1[Anilist4Net.Enums.Seasons]. Path: $.data.Media.season | LineNumber: 0 | BytePositionInLine: 1233.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter1.ReadWithQuotes(Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.EnumConverter1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.NullableConverter1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfo1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader,
Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at GraphQL.Client.Http.GraphQLHttpClient.SendHttpRequestAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
   at GraphQL.Client.Http.GraphQLHttpClient.SendQueryAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
   at Anilist4Net.Client.GetMediaById(Int32 id)

**Comment by yellowsink** [comment]
thanks for letting me know, i will look into this!

**Comment by yellowsink** [comment]
which ID did you search with?

**Comment by SylveonDeko** [comment]
Once I get home I'll find the ID it errored on, it was more than one anime
(I'm using it as part of a findanime command in discord)

**Comment by yellowsink** [comment]
ok cool thanks

**Comment by SylveonDeko** [comment]
MalId 32673 is failing

**Comment by SylveonDeko** [comment]
i tried this with anilist id as well

**Comment by yellowsink** [comment]
fixed in 96d5d742 - if an ID returns 404, the client will now return null.

**Comment by SylveonDeko** [comment]
Will this be pushed to nuget?

**Comment by yellowsink** [comment]
Huh that didnt fix it what

**Comment by SylveonDeko** [comment]
The actual issue is that the season itself is null, I looked it up on mal and it exists

**Comment by yellowsink** [comment]
> Will this be pushed to nuget?

will be once i fix it properly since apparently that didnt work :\

**Comment by SylveonDeko** [comment]
https://myanimelist.net/anime/32673

**Comment by yellowsink** [comment]
> The actual issue is that the season itself is null, I looked it up on mal and it exists

oh i see weird

**Comment by SylveonDeko** [comment]
Also if you have a discord can we talk there? I'm more comfortable with it

**Comment by yellowsink** [comment]
uh i dont really have a discord for anilist4net. I mean i guess theres the discord for gord? https://discord.gg/e4HnvY28Wq

**Comment by SylveonDeko** [comment]
Alright joining it, name is ZeroNyan

**Comment by yellowsink** [comment]
Fixed in f89e7e87fa98b7d433cab74caa1717d0991e5cb3 and https://www.nuget.org/packages/Anilist4Net/1.2.0
